### ISSUE TITLE
Search no longer working

### ISSUE THREAD

**Issue by rkclement** [citelao/Spotify-for-Alfred#107] opened 2017-09-12 18:20 UTC
I can no longer search from the Alfred bar. I get an error code:

`fetch() failed; error code: 401`

here's the log from this error:

```
# Error Log # 
## Error Info ## 
fetch() failed; error code: 401
Line 29, /Users/USER/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.445EA92E-2C6B-411C-B7D8-3379AD4DBDC6/src/citelao/OhAlfred/HTTP/Fetcher.php

## Symbols ## 
Array
(
    [message] => fetch() failed; error code: 401
    [vars] => 
    [0] => Array
        (
            [file] => /Users/USER/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.445EA92E-2C6B-411C-B7D8-3379AD4DBDC6/src/citelao/OhAlfred/HTTP/JsonFetcher.php
            [line] => 15
            [function] => run
            [class] => OhAlfred\HTTP\Fetcher
            [type] => ->
            [args] => Array
                (
                )

        )

    [1] => Array
        (
            [file] => /Users/USER/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.445EA92E-2C6B-411C-B7D8-3379AD4DBDC6/src/citelao/Spotifious/Menus/Search.php
            [line] => 29
            [function] => run
            [class] => OhAlfred\HTTP\JsonFetcher
            [type] => ->
            [args] => Array
                (
                )

        )

    [2] => Array
        (
            [file] => /Users/USER/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.445EA92E-2C6B-411C-B7D8-3379AD4DBDC6/src/citelao/Spotifious/Spotifious.php
            [line] => 129
            [function] => __construct
            [class] => Spotifious\Menus\Search
            [type] => ->
            [args] => Array
                (
                    [0] => jump
                )

        )

    [3] => Array
        (
            [file] => /Users/USER/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.445EA92E-2C6B-411C-B7D8-3379AD4DBDC6/main.php
            [line] => 23
            [function] => run
            [class] => Spotifious\Spotifious
            [type] => ->
            [args] => Array
                (
                    [0] => jump
                )

        )

)
```

EDIT: so it's clear - play/pause from the Alfred bar still works for me. just not search.

**Comment by citelao** [comment] 2017-10-08 02:18
I got that error on and off... has it gone away? Otherwise I'll dive into it.

**Comment by rkclement** [comment] 2017-10-16 20:20
Nope, the error is still there - just checked again.

**Comment by citelao** [comment] 2017-10-23 05:20
I would recommend trying to login to your Spotify application again (In the settings menu, `s`), and if that doesn't work, try re-linking your Spotify application.

Sorry for the slow response!

**Comment by rkclement** [comment] 2017-10-24 20:30
Tried re-logging in, and then tried deleted my Spotify app and creating a new one. Still no luck.

**Comment by citelao** [comment] 2017-10-25 04:11
I'm wondering if it's a misconfigured app (somehow?) or Spotifious, since I cannot reproduce this issue. Can you:

1. Open `~/Library/Application Support/Alfred 3/Workflow Data/com.citelao.spotifious/settings.plist`
2. Copy the `spotify_access_token` and paste it into the `OAuthToken` field [on the Spotify API tester](https://developer.spotify.com/web-api/console/get-album/?id=0sNOF9WDwhWunNAHPD3Baj)
3. Copy and paste the `Response` here.

Thanks! Let's get this fixed :)

**Comment by kupkovski** [comment] 2019-04-24 13:33
it worked out for me as well ☝️ 
Thanks!

**Comment by citelao** [comment] 2019-04-24 16:06
> it worked out for me as well ☝️
> Thanks!

That's great, @kupkovski! Do you mean logging in again or my diagnostic steps (using the Spotify API tester)?

**Comment by citelao** [comment] 2022-01-17 23:25
Closing this since we were never able to diagnose it.

**Closed by citelao** 2022-01-17 23:25 UTC
